version: '3'

services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6543:5432"

  enstore:
    image: 'ghcr.io/ricsam/enstore-server:latest'
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password
    ports:
      - "3456:3000"
