import React from "react";
import { Box, Button, Card, CardActions, CardContent, Dialog, DialogContent, DialogTitle, FormControlLabel, Link as MuiLink, Stack, Switch, TextField, Tooltip, Typography } from "@mui/material";
import { createFileRoute } from "@richie-router/react";
import { useQueryClient } from "@tanstack/react-query";
import { api } from "~/api";
import { JsonEditor, ReadOnlyEditor } from "~/components/Editor";
import { Loading } from "~/components/Loading";
import { RunDetails } from "~/components/RunDetails";
import { RouteLink } from "~/components/RouteLink";
import { Status } from "~/components/Status";

export const Route = createFileRoute("/schedules/$scheduleId/")({ component: ScheduleDetails });
const inputDate = (value: Date | string) => new Date(value).toISOString().slice(0, 16);

function ScheduleDetails() {
  const { scheduleId } = Route.useParams();
  const id = Number(scheduleId);
  const queryClient = useQueryClient();
  const query = api.getSchedule.useQuery({ queryKey: ["schedule", id], queryData: { params: { id } }, refetchInterval: 3000 });
  const update = api.updateSchedule.useMutation({ onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["schedule", id] }) });
  const [editing, setEditing] = React.useState(false);
  const [editingData, setEditingData] = React.useState(false);
  const [dataDraft, setDataDraft] = React.useState("");
  const [dataValid, setDataValid] = React.useState(true);
  const [dataError, setDataError] = React.useState("");
  if (!query.data) return <Loading />;
  const schedule = query.data.payload;
  const dataSchema = typeof schedule.jobDefinition === "string" ? undefined : schedule.jobDefinition.jsonSchema;
  const openDataEditor = () => {
    setDataDraft(schedule.data ? JSON.stringify(JSON.parse(schedule.data), null, 2) : "{}");
    setEditingData(true);
  };
  return <Box>
    <Box display="flex" gap={3} flexWrap="wrap" id="SchedulePage">
      <Card data-testid="schedule-details" sx={{ flex: 1, minWidth: 340 }}><CardContent><Typography variant="h5" gutterBottom>Details</Typography><Box display="grid" gridTemplateColumns="auto 1fr" gap={1} columnGap={2}><Typography color="text.secondary">Status</Typography><Status value={schedule.status} /><Typography color="text.secondary">Next run</Typography><Tooltip title={schedule.runAt ? new Date(schedule.runAt).toISOString() : ""}><Typography data-testid="next-run">{schedule.runNow ? "Scheduled to run now" : schedule.runAt ? new Date(schedule.runAt).toLocaleString() : <>Not scheduled, click <MuiLink component="button" data-testid="no-run-at-edit" disabled={!schedule.capabilities.edit} onClick={() => setEditing(true)}>here</MuiLink> to schedule</>}</Typography></Tooltip><Typography color="text.secondary">Title</Typography><Typography data-testid="schedule-title">{schedule.title}</Typography><Typography color="text.secondary">Description</Typography><Typography data-testid="schedule-description">{schedule.description || "-"}</Typography><Typography color="text.secondary">Definition</Typography>{typeof schedule.jobDefinition === "string" ? <Typography>{schedule.jobDefinition}</Typography> : <MuiLink component={RouteLink} to={`/definitions/${schedule.jobDefinition.id}`} data-testid="definition-link">{schedule.jobDefinition.title} (v{schedule.jobDefinition.version})</MuiLink>}{schedule.cronExpression && <><Typography color="text.secondary">CRON</Typography><Typography>{schedule.cronExpression}</Typography></>}<Typography color="text.secondary">Created</Typography><Typography>{new Date(schedule.createdAt).toLocaleString()}</Typography><Typography color="text.secondary">Number of runs</Typography><Typography data-testid="number-of-runs">{schedule.numRuns}</Typography><Typography color="text.secondary">Retry failed jobs</Typography><Typography data-testid="retry-failed-jobs">{schedule.retryFailedJobs ? "Yes" : "No"}</Typography>{schedule.retryFailedJobs && <><Typography color="text.secondary">Max retries</Typography><Typography data-testid="max-retries">{schedule.maxRetries === -1 ? "Unlimited" : schedule.maxRetries}</Typography><Typography color="text.secondary">Num retries</Typography><Typography data-testid="num-retries">{schedule.retries === -1 ? "None" : schedule.retries}</Typography></>}</Box></CardContent><CardActions><Button data-testid="edit-details" onClick={() => setEditing(true)}>Update</Button></CardActions></Card>
      {schedule.data && <Card data-testid="data-card" sx={{ flex: 1, minWidth: 340 }}><CardContent><Typography variant="h5" gutterBottom>Data</Typography><Typography color="text.secondary" mb={1}>Data passed to {typeof schedule.jobDefinition === "string" ? schedule.jobDefinition : schedule.jobDefinition.title}.</Typography><ReadOnlyEditor language="json" value={JSON.stringify(JSON.parse(schedule.data), null, 2)} /></CardContent>{schedule.capabilities.edit && <CardActions><Button data-testid="submit-edit-data" onClick={openDataEditor}>Edit data</Button></CardActions>}</Card>}
    </Box>
    {schedule.lastRun && <Box mt={3}><Typography variant="h5">Last run</Typography><Typography color="text.secondary" mb={2}>This is the latest run. <MuiLink component={RouteLink} to={`/schedules/${id}/runs/${schedule.lastRun.id}`}>Run #{schedule.lastRun.id}</MuiLink></Typography><RunDetails run={{ ...schedule.lastRun, jobSchedule: schedule, jobDefinition: schedule.jobDefinition, worker: "Worker", capabilities: { view: true, viewLogs: false, delete: false } }} /></Box>}
    <Dialog open={editing} onClose={() => setEditing(false)} maxWidth="sm" fullWidth><DialogTitle>Update details</DialogTitle><DialogContent><Box component="form" data-testid="edit-details-form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const runAt = String(form.get("runAt") ?? ""); update.mutate({ params: { id }, body: { title: String(form.get("title")), description: String(form.get("description")) || null, runAt: runAt ? new Date(runAt) : null, retryFailedJobs: form.get("retryFailedJobs") === "on", maxRetries: Number(form.get("maxRetries")) } }, { onSuccess: () => setEditing(false) }); }}><TextField margin="normal" fullWidth defaultValue={schedule.title} name="title" label="Title" inputProps={{ "data-testid": "title-field" }} /><TextField margin="normal" fullWidth defaultValue={schedule.description} name="description" label="Description" inputProps={{ "data-testid": "description-field" }} /><Stack direction="row" alignItems="flex-end" gap={1}><TextField margin="normal" fullWidth defaultValue={schedule.runAt ? inputDate(schedule.runAt) : ""} name="runAt" type="datetime-local" label="Next run (local time)" InputLabelProps={{ shrink: true }} inputProps={{ "data-testid": "runAt-field" }} /><Button data-testid="unschedule" onClick={(event) => { const form = event.currentTarget.closest("form"); const input = form?.querySelector<HTMLInputElement>('[name="runAt"]'); if (input) { input.value = ""; input.dispatchEvent(new Event("input", { bubbles: true })); } }}>Unschedule</Button></Stack><FormControlLabel control={<Switch defaultChecked={schedule.retryFailedJobs} name="retryFailedJobs" />} label="Retry failed jobs" /><TextField margin="normal" fullWidth defaultValue={schedule.maxRetries} name="maxRetries" label="Max retries" type="number" /><Stack direction="row" justifyContent="flex-end" gap={1} mt={2}><Button onClick={() => setEditing(false)}>Cancel</Button><Button type="submit" data-testid="submit" variant="contained">Save</Button></Stack></Box></DialogContent></Dialog>
    <Dialog open={editingData} onClose={() => setEditingData(false)} maxWidth="md" fullWidth><DialogTitle>Update data</DialogTitle><DialogContent><Box pt={1}><JsonEditor value={dataDraft} onChange={setDataDraft} jsonSchema={dataSchema} height={420} globalEditorRefName="scheduleDataEditor" ariaLabel="Schedule data" onValidationChange={(valid, message) => { setDataValid(valid); setDataError(message ?? ""); }} />{dataError && <Typography color="error" variant="caption" component="pre" whiteSpace="pre-wrap">{dataError}</Typography>}<Stack direction="row" justifyContent="flex-end" gap={1} mt={2}><Button onClick={() => setEditingData(false)}>Cancel</Button><Button variant="contained" disabled={!dataValid || update.isPending} onClick={() => update.mutate({ params: { id }, body: { data: dataDraft, runAt: schedule.runAt ?? null } }, { onSuccess: () => setEditingData(false) })}>Save data</Button></Stack></Box></DialogContent></Dialog>
  </Box>;
}
