apiVersion: v1
kind: Secret
metadata:
  name: secrets
  labels:
    {{- include "enschedule.labels" . | nindent 4 }}
type: Opaque
data:
  pgPassword: {{ .Values.config.pgPassword | b64enc | quote }}
  enstoreUsername: {{ .Values.config.enstoreUsername | b64enc | quote }}
  enstorePassword: {{ .Values.config.enstorePassword | b64enc | quote }}
  accessTokenSecret: {{ .Values.config.accessTokenSecret | b64enc | quote }}
  refreshTokenSecret: {{ .Values.config.refreshTokenSecret | b64enc | quote }}
  cookieSessionSecret: {{ .Values.config.cookieSessionSecret | b64enc | quote }}
  apiKey: {{ .Values.config.apiKey | b64enc | quote }}
  adminAccount: {{ .Values.config.adminAccount | b64enc | quote }}
  nafsUri: {{ printf "enstore://%s:%s?endpoint=http://storage-service:3456" .Values.config.enstoreUsername .Values.config.enstorePassword | b64enc | quote }}
