{{- if .Values.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: storage-service
  labels:
    {{- include "enschedule.labels" . | nindent 4 }}
spec:
  type: {{ .Values.storage.service.type }}
  ports:
    - port: {{ .Values.storage.service.port }}
      targetPort: storage
      protocol: TCP
      name: storage
  selector:
    app.kubernetes.io/name: storage
{{- end }}
