{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: worker-service
  labels:
    {{- include "enschedule.labels" . | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    - port: {{ .Values.worker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: worker
{{- end }}
