apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enschedule.fullname" . }}-worker-config
  labels:
    {{- include "enschedule.labels" . | nindent 4 }}
data:
  functions.js: |
    {{- .Files.Get "files/functions.js" | nindent 4 }}
