version: '3.9'

services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
  worker:
    depends_on:
      postgres:
        condition: service_healthy
    image: 'ghcr.io/ricsam/enschedule-worker:latest'
    environment:
      - POSTGRES=true
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - ENSCHEDULE_API_KEY=secret_key
      - ENSCHEDULE_API=true
      - ENSCHEDULE_API_PORT=3000
      - ENSCHEDULE_API_HOSTNAME=worker
      - DB_PORT=5432
      - DEBUG=pg-driver
      - ENSCHEDULE_ACCESS_TOKEN_SECRET=secret_key
      - ENSCHEDULE_REFRESH_TOKEN_SECRET=secret_key
    volumes:
      - "${PWD}/charts/enschedule/files:/app/packages/worker/definitions"
  dashboard:
    depends_on:
      postgres:
        condition: service_healthy
      worker:
        condition: service_started
    image: 'ghcr.io/ricsam/enschedule-dashboard:latest'
    ports:
      - "8008:3000"
    environment:
      - ENSCHEDULE_COOKIE_SESSION_SECRET=s3cr3t
      - ENSCHEDULE_API_KEY=secret_key
      - ENSCHEDULE_WORKER_URL=http://worker:3000
      - DEBUG=worker-api
      - NODE_ENV=production
      - ENSCHEDULE_ACCESS_TOKEN_SECRET=secret_key
      - ENSCHEDULE_REFRESH_TOKEN_SECRET=secret_key
